### ISSUE TITLE
Start contribution

### ISSUE THREAD

**Issue by prakamya-mishra** [aimacode/aima-julia#11]
I want to start contributing to this repository so please guide me how to do so.

**Comment by mikhail-j** [comment]
You can look into the [CONTRIBUTING.md](https://github.com/mikhail-j/aima-julia/blob/master/CONTRIBUTING.md) file.

Currently, none of the IJulia notebooks are not implemented yet.

To setup your environment for Jupyter notebooks, please install the [IJulia package](https://github.com/JuliaLang/IJulia.jl).

For reference, you can look at the following Jupyter notebooks ([IPython aima-python notebooks](https://github.com/aimacode/aima-python/search?l=Jupyter+Notebook&type=&utf8=%E2%9C%93)
 and [existing IJulia notebooks](https://github.com/JuliaDiffEq/DiffEqTutorials.jl)).

**Comment by mikhail-j** [comment]
@prakamya-mishra Sorry, I forgot to tag you.
