### ISSUE TITLE
Julia 0.5->0.6

### ISSUE THREAD

**Issue by femtotrader** [aimacode/aima-julia#14]
Hello,

This https://github.com/JuliaLang/julia/blob/release-0.6/NEWS.md should help migrating code from Julia 0.5 to 0.6

Using this GitHub bot
https://github.com/JuliaComputing/FemtoCleaner.jl
should help to remove a lot of deprecated syntax.

Here is build status https://travis-ci.org/aimacode/aima-julia/jobs/293646584

Kind regards

**Comment by mikhail-j** [comment]
@femtotrader I have fixed all deprecation warnings encountered between v0.5 and v0.6 for Base.Test tests.
