### ISSUE TITLE
Anyone working on this? 

### ISSUE THREAD

**Issue by Vaibhavdixit02** [aimacode/aima-julia#7]
Is anyone still working on the Julia implementations or has it been scrapped?

**Comment by mikhail-j** [comment]
No, this project has not been scrapped.

I am still working on this project, I will push some changes soon.

**Comment by Vaibhavdixit02** [comment]
Great!

**Comment by Ridhwanluthra** [comment]
why was this project scrapped??

**Comment by mikhail-j** [comment]
This project is not scrapped.

I am working on this.
